# This file was generated by GoReleaser. DO NOT EDIT.
cask "enplace" do
  version "1.7.0"

  on_macos do
    on_intel do
      sha256 "9610bbb88abcbd96035d7dd9646de1e44791a7450b5a412ea377ea4adb51fe60"
      url "https://github.com/djcp/enplace/releases/download/v#{version}/enplace_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e6cd54d35757d021e3c7538dce69d0c57447cc532b56327f5f8121d19a1af726"
      url "https://github.com/djcp/enplace/releases/download/v#{version}/enplace_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e2c3885dbd51f769c029b98bc836df630e551780c196eab1c73e47f238955646"
      url "https://github.com/djcp/enplace/releases/download/v#{version}/enplace_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4bbf8c6c11517fc02b6fac26d796f8c9aaf498f1a6fa36edf1526b540359756a"
      url "https://github.com/djcp/enplace/releases/download/v#{version}/enplace_#{version}_linux_arm64.tar.gz"
    end
  end

  name "enplace"
  desc "A CLI recipe manager powered by Claude AI"
  homepage "https://github.com/djcp/enplace"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "enplace"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/enplace"]
    end
  end

  # No zap stanza required

end
