# This file was generated by GoReleaser. DO NOT EDIT.
cask "enplace" do
  version "1.5.0"

  on_macos do
    on_intel do
      sha256 "f92004ce96a0c3f7aa43996b5baa401e6398f7a66353729f6923a87e5ec67a24"
      url "https://github.com/djcp/enplace/releases/download/v#{version}/enplace_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "87d6006c778d1697d571f31bdf2e2ef00655928fef4351f6a44117124eb3bc1d"
      url "https://github.com/djcp/enplace/releases/download/v#{version}/enplace_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "96b860970fe45e2f8db2171e76d667db23f5b50401dd04bd7f712c2e0e2b6ba1"
      url "https://github.com/djcp/enplace/releases/download/v#{version}/enplace_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1bfd143d97e78bf39fd6a09bb41348b57ea8de6ca761025653a2d69c1ba64b1e"
      url "https://github.com/djcp/enplace/releases/download/v#{version}/enplace_#{version}_linux_arm64.tar.gz"
    end
  end

  name "enplace"
  desc "A CLI recipe manager powered by Claude AI"
  homepage "https://github.com/djcp/enplace"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "enplace"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/enplace"]
    end
  end

  # No zap stanza required

end
