# This file was generated by GoReleaser. DO NOT EDIT.
cask "enplace" do
  version "1.5.1"

  on_macos do
    on_intel do
      sha256 "e1e4f3bd6d083ad453f7c6e98783824a21c92a2997468b4048cb370959eba2e8"
      url "https://github.com/djcp/enplace/releases/download/v#{version}/enplace_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8073bf08e87cffda0692faf578fff1805f3a12226d2cb0102159162acdef41f1"
      url "https://github.com/djcp/enplace/releases/download/v#{version}/enplace_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "70548792c6dd0b90e3e75b83a1c83d36d692542fbd6934b4ce3fc7240af5b31a"
      url "https://github.com/djcp/enplace/releases/download/v#{version}/enplace_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a2fc4134ebec3d8840c889b373310742e0b1f956bdc9e13f497bdcbc6414ffa5"
      url "https://github.com/djcp/enplace/releases/download/v#{version}/enplace_#{version}_linux_arm64.tar.gz"
    end
  end

  name "enplace"
  desc "A CLI recipe manager powered by Claude AI"
  homepage "https://github.com/djcp/enplace"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "enplace"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/enplace"]
    end
  end

  # No zap stanza required

end
